#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

cd $GIT_DIR
if [ -f dodo.py ]
then
    echo Dodo file present.
    if [ ! -d rebase-merge ]
    then
        echo Running doit:
        source ~/.virtualenvs/linkedin/bin/activate
        doit -n 7 --continue --verbosity=0 &> doit.log &
    fi
else
    echo Skipping doit.
fi
